// src/utils/topics.js

// I've parsed your JSON string into a clean, de-duplicated array.
export const topics = [
  "Animals", "Birds", "Dinosaurs", "Ocean Life", "Insects", "Reptiles", "Mammals",
  "Amphibians", "Fish", "Endangered Species", "National Parks", "Mountains",
  "Rivers", "Deserts", "Forests", "Weather", "Climate", "Natural Disasters",
  "Planets", "Stars", "Galaxies", "The Moon", "The Sun", "Space Exploration",
  "Astronomy Basics", "Comets and Meteors", "Constellations", "Solar System",
  "Black Holes", "Nebulae", "Famous Scientists", "Inventions", "Technology",
  "Computers", "Internet Safety", "Coding Basics", "Robots", "Artificial Intelligence",
  "Engineering Marvels", "Transportation", "Cars", "Trains", "Airplanes", "Ships",
  "Bicycles", "Famous Landmarks", "World Wonders", "Historic Monuments", "Architecture",
  "Famous Buildings", "Castles", "Bridges", "Tunnels", "Skyscrapers", "Geography",
  "Countries", "Capitals", "Continents", "Oceans", "Islands", "Maps and Globes",
  "Flags of the World", "Languages", "Currencies", "Time Zones", "Latitude and Longitude",
  "Famous Explorers", "Ancient Civilizations", "Egyptian Pyramids", "Greek Mythology",
  "Roman Empire", "Vikings", "Medieval Times", "Renaissance", "Industrial Revolution",
  "Famous Inventors", "Historical Events", "World Records", "Olympic Games", "Sports",
  "Baseball", "Basketball", "Soccer", "Tennis", "Swimming", "Gymnastics",
  "Track and Field", "Winter Sports", "Olympic History", "Famous Athletes",
  "Team Sports", "Individual Sports", "Sports Equipment", "Sports Rules",
  "Healthy Living", "Nutrition", "Exercise", "Hydration", "Sleep", "Mental Wellness",
  "First Aid Basics", "Human Body", "Senses", "Digestive System", "Circulatory System",
  "Respiratory System", "Nervous System", "Skeletal System", "Muscular System",
  "Genetics", "Growth and Development", "Dental Health", "Vision and Hearing",
  "Medicine", "Vaccines", "Germs and Hygiene", "Plants", "Trees", "Flowers",
  "Gardening", "Photosynthesis", "Pollination", "Ecosystems", "Food Chains",
  "Habitats", "Conservation", "Recycling", "Renewable Energy", "Water Cycle", "Soil",
  "Fungi", "Seeds and Spores", "Seasons", "Spring", "Summer", "Autumn", "Winter",
  "Holidays Around the World", "Christmas Traditions", "Easter", "Halloween",
  "Thanksgiving", "New Year’s", "Diwali", "Chinese New Year", "Hanukkah",
  "Ramadan and Eid", "Cultural Festivals", "Traditional Clothing", "World Cuisines",
  "Famous Dishes", "Baking", "Cooking Basics", "Kitchen Safety", "Food Groups",
  "Fruits", "Vegetables", "Grains", "Dairy", "Proteins", "Herbs and Spices",
  "Food Origins", "Famous Chefs", "Art", "Painting", "Sculpture", "Drawing",
  "Color Theory", "Famous Artists", "Art Movements", "Photography", "Digital Art",
  "Crafts", "Origami", "Pottery", "Music", "Instruments", "Classical Music", "Jazz",
  "Pop Music", "Rock Music", "Country Music", "Folk Music", "Music Theory",
  "Famous Composers", "Singing", "Dance", "Ballet", "Hip Hop", "Tap Dance",
  "Cultural Dances", "Theater", "Broadway", "Shakespeare", "Famous Plays", "Acting",
  "Puppetry", "Magic Tricks", "Jokes and Riddles", "Board Games", "Card Games",
  "Puzzles", "Crosswords", "Sudoku", "Mazes", "Word Games", "Memory Games",
  "Strategy Games", "Video Games (Family-Friendly)", "Outdoor Games",
  "Indoor Games", "Scavenger Hunts", "Treasure Hunts", "Nature Walks", "Camping",
  "Hiking", "Birdwatching", "Stargazing", "Fishing", "Boating", "Swimming Safety",
  "Pet Care", "Dog Breeds", "Cat Breeds", "Small Pets", "Aquariums",
  "Animal Behavior", "Animal Communication", "Animal Habitats", "Zoos and Sanctuaries",
  "Wildlife Photography", "Famous Animals in History", "Animal Superlatives",
  "Baby Animals", "Animal Adaptations", "Migration Patterns", "Hibernation",
  "Camouflage", "Mimicry", "Predators and Prey", "Symbiosis", "Extinct Animals",
  "Fossils", "Paleontology", "Geology", "Rocks and Minerals", "Volcanoes",
  "Earthquakes", "Caves", "Crystals", "Soil Layers", "Fossils and Fossilization",
  "Earth’s Layers", "Tectonic Plates", "Natural Resources", "Water Conservation",
  "Air Quality", "Pollution Prevention", "Green Living", "Sustainable Practices",
  "Eco-Friendly Products", "Composting", "Gardening for Kids", "Butterfly Gardens",
  "Bird Feeders", "Backyard Wildlife", "Farm Animals", "Crops", "Harvesting",
  "Agriculture", "Bees and Beekeeping", "Honey", "Maple Syrup", "Chocolate",
  "Coffee and Tea", "Bread Making", "Cheese Making", "Yogurt", "Ice Cream",
  "Candy", "Snacks Around the World", "Breakfast Foods", "Lunch Ideas",
  "Dinner Dishes", "Desserts", "Beverages", "Smoothies", "Juices", "Water Facts",
  "Milk and Alternatives", "Famous Food Brands", "Food Packaging", "Food Labels",
  "Allergies and Sensitivities", "Food Safety", "Kitchen Tools", "Table Manners",
  "Picnics", "Barbecues", "Baking Science", "Cooking Measurements", "Recipe Reading",
  "Food Preservation", "Canning", "Freezing", "Drying", "Fermentation", "Pickling",
  "Food History", "Ancient Diets", "Medieval Food", "Colonial Cooking",
  "Victorian Era Meals", "20th Century Food Trends", "Future Foods", "Space Food",
"Edible Insects", "Vertical Farming", "Hydroponics", "Aquaponics",
  "Urban Gardening", "School Gardens", "Community Gardens", "Farmers Markets",
  "Local Food", "Organic Food", "Fair Trade", "Food Waste",
  "Hunger and Nutrition Programs", "Cooking Shows", "Food Documentaries",
  "Culinary Schools", "Food Festivals", "Street Food", "Food Trucks",
  "Restaurant Types", "Menu Reading", "Tipping Etiquette", "Dining Customs",
  "Table Settings", "Napkin Folding", "Food Presentation", "Plating Techniques",
  "Garnishes", "Sauces and Dressings", "Spices Around the World", "Herb Gardens",
  "Medicinal Plants", "Poisonous Plants", "Carnivorous Plants", "Succulents",
  "Cacti", "Orchids", "Roses", "Tulips", "Sunflowers", "Lavender", "Mint",
  "Basil", "Rosemary", "Thyme", "Parsley", "Cilantro", "Dill", "Oregano",
  "Sage", "Chives", "Bay Leaves", "Vanilla", "Cinnamon", "Nutmeg", "Cloves",
  "Ginger", "Turmeric", "Paprika", "Cumin", "Coriander", "Cardamom", "Saffron",
  "Pepper", "Salt", "Sugar", "Honey Varieties", "Maple Grades", "Olive Oil",
  "Vinegar Types", "Mustard", "Ketchup", "Mayonnaise", "Soy Sauce", "Hot Sauce",
  "Barbecue Sauce", "Salad Dressings", "Dips and Spreads", "Nut Butters",
  "Jams and Jellies", "Pickles", "Olives", "Nuts and Seeds", "Dried Fruits",
  "Granola", "Cereal", "Oatmeal", "Pancakes", "Waffles", "French Toast", "Eggs",
  "Bacon", "Sausage", "Hash Browns", "Bagels", "Donuts", "Muffins", "Scones",
  "Croissants", "Bread Types", "Pasta Shapes", "Rice Varieties", "Beans and Legumes",
  "Lentils", "Tofu", "Tempeh", "Seitan", "Quinoa", "Bulgur", "Couscous",
  "Polenta", "Grits", "Cornmeal", "Flour Types", "Yeast", "Baking Powder",
"Baking Soda", "Vanilla Extract", "Food Coloring", "Sprinkles", "Candy Making",
  "Chocolate Types", "White Chocolate", "Milk Chocolate", "Dark Chocolate",
  "Cocoa Powder", "Hot Chocolate", "Milkshakes", "Floats", "Slushies",
  "Lemonade", "Iced Tea", "Fruit Punch", "Smoothie Bowls", "Acai Bowls",
  "Chia Pudding", "Yogurt Parfaits", "Granola Bars", "Trail Mix", "Energy Balls",
  "Protein Shakes", "Meal Prep", "Lunchbox Ideas", "Snack Packs",
  "After-School Snacks", "Party Snacks", "Game Day Food", "Movie Night Treats",
  "Birthday Cake", "Cupcakes", "Cookies", "Brownies", "Bars", "Pies", "Tarts",
  "Cobblers", "Crisps", "Puddings", "Mousses", "Soufflés", "Ice Cream Flavors",
  "Frozen Yogurt", "Gelato", "Sorbet", "Sherbet", "Popsicles", "Ice Pops",
  "Slush Puppies", "Snow Cones", "Cotton Candy", "Caramel Apples", "Popcorn",
  "Pretzels", "Chips", "Crackers", "Cheese Puffs", "Nuts", "Seeds"
];